### ISSUE TITLE
postCreateCommand fails on opeing repo in Remote-Container

### ISSUE THREAD

**Issue by Sholofly** [ludeeus/container#307]
When opening the repository as Remote-Container in VSCode i get an error:

`postCreateCommand failed with exit code 2. Skipping any further user-provided commands.`

As a result I can't use the CLI. All container commands returning something like:

```
root ➜ /workspaces/container (main) $ container init
make: *** No rule to make target 'init'.  Stop.
root ➜ /workspaces/container (main) $ 
```

**** log ****
```
bash include
include: include: Is a directory
make: *** [Makefile:9: init] Error 126
[245824 ms] postCreateCommand failed with exit code 2. Skipping any further user-provided commands.
[245824 ms] Error: Command failed: /bin/sh -c make init
[245824 ms]     at dL (c:\Users\rudolf\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1683:137)
[245825 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[245825 ms]     at async Promise.all (index 0)
[245825 ms]     at async wg (c:\Users\rudolf\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1676:3580)
[245825 ms]     at async xg (c:\Users\rudolf\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1676:2837)
[245825 ms]     at async wae (c:\Users\rudolf\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1994:22003)
[245825 ms]     at async xae (c:\Users\rudolf\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1994:19839)
[245836 ms] Exit code 1
[245836 ms] Command failed: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\rudolf\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js run-user-commands --user-data-folder c:\Users\rudolf\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\_git\private\container --id-label devcontainer.local_folder=c:\_git\private\container --container-id f9d20a322dd460553202b6b557c949e9d050ad64c7e2846824d443f3401d53d9 --log-level debug --log-format json --config c:\_git\private\container\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --skip-non-blocking-commands false --prebuild false --stop-for-personalization true --remote-env SSH_AUTH_SOCK=/tmp/vscode-ssh-auth-633bb7631a244f41431686d7ba71b53e29adaf0d.sock --remote-env REMOTE_CONTAINERS_IPC=/tmp/vscode-remote-containers-ipc-633bb7631a244f41431686d7ba71b53e29adaf0d.sock --remote-env REMOTE_CONTAINERS=true --mount-workspace-git-root true --terminal-columns 218 --terminal-rows 13
```

**Comment by ludeeus** [comment]
Only `container help` should work. and it does.
do `container` to list possible commands

**Comment by Sholofly** [comment]
Thanks, you're right. I misinterpreted the purpose of this repo. Sorry for bothering you on beta day!
